title: Andrea Oriolo
logo: /assets/img/foto_profilo2.jpg
email: oriolo.andre@gmail.com
description: Software Engineer
favicon: true
show_downloads: false
google_analytics: G-TQDGWRYGPQ
#google_analytics: UA-108144808-1
remote_theme: BDHU/minimalist
color-scheme: light
use_math: true
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-remote-theme

sidebar:
  - name: GitHub
    icon: fa-brands fa-github
    link: 
  - name: Twitter
    icon: 
    link: 
